### ISSUE TITLE
Ability to change postgres log settings 

### ISSUE THREAD

**Issue by cod-r** [cloudnative-pg/cloudnative-pg#1085]
Hi,

We're trying to migrate from zalando operator and we are facing a problem with the logs.
We are using pgBadger to analyze logs generated by postgres.

In zalando the logs are saved in the container (and in a PVC) for one week and rotated:
```sh
root@zalando-cluster-0:/home/postgres/pgdata/pgroot/pg_log# ls
postgresql-0.csv  postgresql-1.log  postgresql-2.log  postgresql-3.log  postgresql-4.log  postgresql-5.log  postgresql-6.log  postgresql-7.log
postgresql-1.csv  postgresql-2.csv  postgresql-3.csv  postgresql-4.csv  postgresql-5.csv  postgresql-6.csv  postgresql-7.csv 
```
Using these log files we can run pgBadger without any issue.

The problem is that CNPG throws the logs to stdout without saving them to a file and rotating them.

We tried to change the postgres setting for the logging but in the docs it says `all log settings in PostgreSQL are fixed and cannot be changed`. So adding `log_truncate_on_rotation = 'on'` fails.

My question is how can I make it save the logs in the container just like zalando does?

**Comment by gbartolini** [comment]
Our design is based on the assumption that we do not store logs in the container, but rather follow the Kubernetes standard so that the application logs in standard output in JSON format directly. See: https://kubernetes.io/docs/concepts/cluster-administration/logging/#how-nodes-handle-container-logs

Specifically, we treat our containers as immutable application containers, rather than a mutable system container in which multiple applications can run inside the container. I understand it is a fundamentally different approach, but it is probably the biggest differentiator between our operator and other operators that work with Postgres.

I suggest you look at the problem by taking a step back, and thinking in Kubernetes terms: this should probably be handled downstream from the operator, using tools like fluentd or similar that reconvert the log from JSON to CSV and have a pod running pgBadger inside. Despite being an early adopter of pgBadger, I must admit I am not anymore up to date with it so I am afraid I cannot provide further help on it.

**Comment by viorel-anghel** [comment]
hi and thanks for your response
while I d your design assumption and that would be probaly great for most users, I don't understand why you cannot be a bit flexible leaving the decision on how to handle logs to the users. the container we'll be still immutable, the logs can be written on the postgres data volume where you want to write data anyways.

**Comment by gbartolini** [comment]
I will express my opinion here, so please take it as is. Happy to hear what other people, including maintainers, think and, in any case, I encourage you to propose a pull request and/or participate in one of the next developer meetings.

IMHO this is not a matter of being flexible or not, rather being cloud native as an application and shift to a new way of managing a database. Being a good citizen in Kubernetes for us has been always a priority: this is the way Kubernetes applications expect to manage logs and it is the way we prioritized when developing the logging framework. Consider also that deliberately in this phase we do not support sidecars (for example to run pgBadger) and volumes (for example to store logs). I would for example think of ways to have pgBadger integrate itself with this cloud native setup, rather than the other way around.

Security wise it is also preferable not to store logs in the container.

Sharing PGDATA with user logs would also impact the lifecycle of the database on a self-healing level: think about the case where those logs would fill the space of PGDATA, potentially causing an avalanche effect on the other instances in the cluster which would inevitably lead to human intervention.

Anyway, I don't want to discourage any attempt in this direction. I just don't agree with this direction, but it is my vote.

**Comment by sxd** [comment]
@viorel-anghel Hi!

If you require to process the logs the proper way will be using a log collector like FluentBit to collect the logs from Pods and the process those logs outside, from there you can store your logs wherever you want without the need of thinking on configure rotation or even delete logs inside the pods! (yes logs use space and sometime you want your PVCs as small as possible).

Using a log collector it's the proper Kubernetes way to collect logs and then do any kind of processing with them, like in your case, use PgBadger, you can export the logs in the format you need with the fields you actually need.

I can see you opened an issue with the PgBadger https://github.com/darold/pgbadger/issues/760 team, if you need a different format for that information you can extract the json and do any task with them after the logs are collected.

Hope this helps you a bit to clarify why the logs use a cloud-native approach for the logs.

**Comment by gbartolini** [comment]
@sxd thanks for your input here - you certainly know more than me on this topic! I forgot about fluentbit for this specific case.

@viorel-anghel - FYI @sxd is a fluentbit developer (he developed the PostgreSQL backend support)

**Comment by gbartolini** [comment]
A good outcome from this issue could be a documentation page that explains how to implement your use case

**Comment by till** [comment]
Other great solutions supporting log collection from pods are Promtail and vector.dev.

**Comment by cod-r** [comment]
Thanks everyone for the insights.

We are using promtail with loki for log collection.
Our solution is to extract the logs from loki using logcli and send them to pgBadger:
1. Extract logs from loki
```sh
docker run --network=host grafana/logcli:2.7.0-amd64 \
  query '{pod="pg-cluster-1"}' \
  --addr=http://loki-addr:3100/ \
  --limit 1000000 \
  --batch 1000 \
  --since=48h \
  -o raw -q > cnpg-logs.json
```
2. Run pgBadger
```sh
pgbadger -f jsonlog cnpg-logs.json
```
pgBadger just added support for cnpg log format: https://github.com/darold/pgbadger/pull/761

I find this solution more expensive than before but at least now we are doing things the cloud native way.

**Comment by gbartolini** [comment]
This is great. Thanks a lot for your contribution. Worth blogging about it! <hint><hint> ;)

**Comment by gbartolini** [comment]
@cod-r would you like to have containers for pgbadger under cloudnative-pg (similarly to the ones we produce for pgbouncer for example)? If you'd like to maintain them, we are more than happy to host the pipelines here.

**Comment by cod-r** [comment]
Now we have a container with pgbadger, logcli and other stuff inside, so we don't need one with pgbadger only. But if there is demand for it then I can help with this.

**Comment by kfkawalec** [comment]
@cod-r Could you share solution with pgbadger ale logcli inside container?
I also send all logs to loki this sounds very interesting, much better than manually exporting log and running pgbadger.

**Comment by viorel-anghel** [comment]
it is nothing particularly nice or kubernetes best practices. basically we run a pod based on an ubuntu image in which we installed all the required tools (pgbadger, logcli, nginx, crond) and in this some shell scripts where the main lines are something like

[...]
timeout 1m logcli query "{pod=\"$pod\"}" --addr=$LOKI --limit 1000000 --batch 1000 --since=25h -o raw -q > cnpg-logs.json

pgbadger -f jsonlog -I -j 1 --exclude-appname pg_dump --exclude-user postgres --last-parsed LAST_PARSED -O $dst cnpg-logs.json
[...]
