### ISSUE TITLE
Deleting testing images are failing

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#151]
The workflow that deletes `-testing` images are failing like here: https://github.com/cloudnative-pg/cloudnative-pg/runs/6430524440?check_suite_focus=true
On the other side, this workflow should run scheduled and on workflow dispatch, but not on push

**Comment by mnencia** [comment]
The job is failing because it has no access to the GitHub PAT secret. You are correct that the workflow should not run on PR, which will solve the issue. I would also change the workflow not to require the secret and to use the standard GitHub token and specify the necessary permission from the workflow YAML.

**Comment by mnencia** [comment]
Unfortunately, the GITHUB_TOKEN is not enough until https://github.com/snok/container-retention-policy/issues/27 is solved (by GitHub)

**Comment by mnencia** [comment]
Closed by #152
