### ISSUE TITLE
Additional mount point inside a pod - feature request

### ISSUE THREAD

**Issue by MichaluxPL** [cloudnative-pg/cloudnative-pg#1669]
Hi,

Sometimes it is necesarry to load some data stored on a filesystem to a database (i.e. to speed up the operation vs transmiting data over network).
It would be great if CNPG allow to mount additional FS in order to enable such and similar actions.

**Comment by itay-grudev** [comment]
@MichaluxPL I had the same problem when I was importing my existing database into CNPG.

What I did is used the fact that PVs are mounted under `/var/lib/postgresql/data/` so I copied my file there:

```bash
kubectl cp database.dump namespace/database-1:/var/lib/postgresql/data/database.dump
```

And thank god for your issue, because I totally forgot to delete it afterwards.

**Comment by MichaluxPL** [comment]
Downloading data directly to PV is not the desired solution. This is storage for the database, so Your soulution would work only if the amount of data to be loaded is quite small. Otherwise You'll have to resize data storage significantly to provide additional space. You want be able to reclaim then space after the operation.
Additional mount point would be perfest for such a solutions.
For the import operation, I've stared some talk to provide some additional, temporary storage on the manifest level. Hopefully it will end up with some nice solution :)

**Comment by MichaluxPL** [comment]
@itay-grudev for the import You can do such a thing quite automatically, using import spec. So no need to copy the dump manually. Of course You still need to ensure the required free space on data volume.

**Comment by itay-grudev** [comment]
@MichaluxPL Basically what you are asking for is for a permanently allocated PV for temporary storage to pods. Database pods are not supposed to be restarted as a fail-over always has downtime, so attaching a temporary volume not really a solution. It will have to be there from the start.

So instead of attaching an additional drive permanently there are two options:

1. Use the drive already attached (admittedly, can be considered a dirty solution, although not really - see below).
2. Manually create a pod on the same node as your primary to perform your workload (although there will still be certain networking costs).

The PostgreSQL data lives inside `/var/lib/postgresql/data/pgdata`, so you won't be interfering with PostgreSQL when adding files or additional directories under `/var/lib/postgresql/data/user/` for example.

What's more data dumps are compressed. In my case the compression ratio is about 12:1. So as long as your data volume is at least 20% larger than your uncompressed data, and given that your data is in fact compressible (typically the case) you should be fine.

The only case where this would be useful would be if:
* your data is highly incompressible
* you only need this extra storage rarely
* you don't mind restarting you database pods and incurring downtime

I think running your workload on an extra pod on the same node or using `/var/lib/postgresql/data/` is the more feasible and universal solution.

**Comment by itay-grudev** [comment]
Oh and I forgot to mention, you will need as many of these extra volumes as nodes in your cluster, as attaching the temporary storage volume will trigger a full cluster update, and the master will change. So the volumes will need to be attached to all pods as you don't really know which one will be the new master.

**Comment by MichaluxPL** [comment]
We have many cases where it is good to have data available directly on the pod. Restarts are not an issue. We can afford the pod to restart in order to mount additional FS with the required data. Since we need such a solution in order to perform particular operations, there is no need to mount it on all cluster's pods.

**Comment by sxd** [comment]
@MichaluxPL why you can't use an external pod that will connect to the primary pod to transfer the data? what's the actual need to have the data in the same pod of the primary pod of the cluster? what if in the meantime that pod dies and another one takes the primary role?
The problem that I can see here, it's that we will add storage to a pod that it will be needed for a short period but that's not how Kubernetes works, the pods are mean to die but the specs needs to be there for ever.
Probably we can think in some kind of solution that will fit all the needs here

**Comment by sxd** [comment]
I'm closing this since it doesn't seem to be an issue and it's more a discussion but now looks like it's fixed
