### ISSUE TITLE
Postgres user password not set during/after import (type monolith)

### ISSUE THREAD

**Issue by MichaluxPL** [cloudnative-pg/cloudnative-pg#1881]
K8s: 1.25.3
CNPG: 1.19.1

Test environment:
One namespace, source cluster (simple manifest, nothing fancy), destination cluster bootstrapped using config:
bootstrap:
    initdb:
      localeCollate: "en_US.UTF-8"
      localeCType: "en_US.UTF-8"
      secret:
        name: testdb-secret
      import:
        type: monolith
        databases:
          - "*"
        roles:
          - "*"
        source:
          externalCluster: test-source
pg_hba:
      - host all postgres 0.0.0.0/0 scram-sha-256
      - hostssl all postgres 0.0.0.0/0 scram-sha-256
      - host all +technical_users 0.0.0.0/0 scram-sha-256
      - hostssl all +technical_users 0.0.0.0/0 scram-sha-256
      - host all +regular_users 0.0.0.0/0 ldap ldapserver=ldap.test ldapport=389 ldaptls=0 ldapprefix="uid=" ldapsuffix=",CN=Users,O=TEST"
      - hostssl all +regular_users 0.0.0.0/0 ldap ldapserver=ldap.test ldapport=389 ldaptls=0 ldapprefix="uid=" ldapsuffix=",CN=Users,O=TEST"
      - host all all 0.0.0.0/0 reject

After destination cluster is provisioned (import correctly finished), postgres user password is empty.
It is not beeing set both when there is superuserSecret provided in the destanation cluster manifest and when operator creates superuser sercret on itself (secret is created but postgres password inside the cluster is still empty).
Looks like a bug to me.

**Comment by MichaluxPL** [comment]
Further investigation showed that probelm exists when there is no database and owner names specified in spec.bootstrap.initdb section of target cluster manifest. Operator tries to import data to database named "app" and looks for a secret for an owner "app". That fails the whole process of setting both postgres and owner passwords (since it runs in one transaction).
I've discussed this issue with one of CPNG devs (@leonardoce) and we've agreed this is a bug to be fixed.

**Comment by leonardoce** [comment]
Yes.

This is happening because `app` is set by the defaulting webhook into the target cluster, while in the proposed secret (`testdb-secret` in this example), the name is different.

The workaround is specifying the `owner` user inside the target database. 

The webhook could be smarter, reading the user's name from the secret, but this will require the operator to reach the API server while being reached by the API server to process a webhook request.
We're thinking to prevent our users to create clusters using monolithic import and a custom secret without specifying the owner name.

Besides this, I'm going to propose a patch that will allow the operator to set the `postgres` password even if the proposed secret is not coherent.

**Comment by sxd** [comment]
Closing, this was fixed here https://github.com/cloudnative-pg/cloudnative-pg/pull/2004 and merged
