### ISSUE TITLE
[Feature] NetworkPolicy for `Cluster` and `Pooler`

### ISSUE THREAD

**Issue by jcpunk** [cloudnative-pg/cloudnative-pg#1963]
It would be nice if there was a default NetworkPolicy for created clusters that only permitted inbound traffic on the expected ports maybe also restricting egress if there are rational limits.  https://cloudnative-pg.io/documentation/1.19/security/#exposed-ports

In theory it could have some "smart bits" that limit access to port 8000 to just and only the operator container(s) or a enable access to the metrics port if and only if the metrics service is started.

Ideally, I'd like to be able to instead provide my own NetworkPolicy if I want something more restrictive - such as "only this namespace can reach port 5432" or "only this container from this namespace can reach the metrics port".

Having the NetworkPolicy with the Cluster/Pooler definition feels like it helps centralize the operational knowledge of how the database(s) should be accessible.

**Comment by sxd** [comment]
hi @jcpunk 

Creating a NetworkPolicy it's out of the scope of the operator, since every network can be managed differently and using a totally different policy or even custom policies, this must be managed and it's up to the Kubernetes cluster administrators, not CloudNativePG

Closing this since it's not in the operator scope.

Regards!

**Comment by jcpunk** [comment]
Is there a list of default port usage for help setting up the policy on the local end?

**Comment by phisco** [comment]
You can have a look here: https://cloudnative-pg.io/documentation/current/security/#network-policies.
Feel free to ping us if you need some clarification.
