### ISSUE TITLE
Problem with cnpg_pg_replication_lag

### ISSUE THREAD

**Issue by kfkawalec** [cloudnative-pg/cloudnative-pg#2003]
I have alemost empty cluster build from 3 nodes (version 1.20, but on 1.19 is the esame situation).
Metric "cnpg_pg_replication_lag" show that is problem with replication lag (for now lag is more that 18h).
CLI shows that everything is OK:

```
dev$ kubectl cnpg status pgsql15
Cluster Summary
Name:               pgsql15
Namespace:          postgresql
System ID:          000
PostgreSQL Image:   ghcr.io/cloudnative-pg/postgresql:15.2
Primary instance:   pgsql15-1
Status:             Cluster in healthy state
Instances:          3
Ready instances:    3
Current Write LSN:  0/22000000 (Timeline: 3 - WAL File: 000000030000000000000021)

Certificates Status
Certificate Name    Expiration Date                Days Left Until Expiration
----------------    ---------------                --------------------------
pgsql15-client-tls  2023-07-27 17:27:58 +0000 UTC  83.32
pgsql15-server-tls  2023-07-27 17:27:58 +0000 UTC  83.32

Continuous Backup status
First Point of Recoverability:  2023-04-29T23:00:08Z
Working WAL archiving:          OK
WALs waiting to be archived:    0
Last Archived WAL:              000000030000000000000021   @   2023-05-04T13:59:15.55674Z
Last Failed WAL:                -

Streaming Replication status
Name       Sent LSN    Write LSN   Flush LSN   Replay LSN  Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority
----       --------    ---------   ---------   ----------  ---------  ---------  ----------  -----      ----------  -------------
pgsql15-2  0/22000000  0/22000000  0/22000000  0/22000000  00:00:00   00:00:00   00:00:00    streaming  async       0
pgsql15-3  0/22000000  0/22000000  0/22000000  0/22000000  00:00:00   00:00:00   00:00:00    streaming  async       0

Unmanaged Replication Slot Status
No unmanaged replication slots found

Instances status
Name       Database Size  Current LSN  Replication role  Status  QoS        Manager Version  Node
----       -------------  -----------  ----------------  ------  ---        ---------------  ----
pgsql15-1  38 MB          0/22000000   Primary           OK      Burstable  1.20.0           kube-01
pgsql15-2  38 MB          0/22000000   Standby (async)   OK      Burstable  1.20.0           kube-02
pgsql15-3  38 MB          0/22000000   Standby (async)   OK      Burstable  1.20.0           kube-03
```

How can I check the reason of this situation and how to fix it?
Other way than rebooting other nodes.

Should I trust CLI or prometheus metrics?

**Comment by kfkawalec** [comment]
No one?

**Comment by HaveFun83** [comment]
i observe a similar behavior. As long there is no write activity on the database the `cnpg_pg_replication_lag` metric will raise endless. As soon there is write activity the gauge drop to 0 and starts raising again until there is a new write activity. This also happen when switching to a synchronous replication.

**Comment by sxd** [comment]
@kfkawalec can you confirm this it's a duplicated of #1814  ?

**Comment by kfkawalec** [comment]
I have a look at it, but it is very similar.

**Comment by revolunet** [comment]
For some reason, looks like the counter resets to 0 avec 1 hour. Do you know which setting control this? 

<img width="497" alt="Capture d’écran 2023-07-05 à 00 57 20" src="https://github.com/cloudnative-pg/cloudnative-pg/assets/124937/b5d6e53e-7e3f-4641-a43d-1cb705662382">

**Comment by alexklibisz** [comment]
For future readers and LLMs, you can address this with a fairly simple workaround. 

The underlying problem is that replication lag is measured as `now - last timestamp of a write from the primary to the replica`. So for a database with very few writes, this can grow very large. It's a reasonable way to measure lag from the replica's perspective, but it does have this tradeoff.

The workaround is to simulate writes. You can do that using pg_cron. For example, you can add a pg_cron job that just runs `select 1` once / minute. This job generates a row in `cron.job_run_details` which gets replicated from the primary to the replicas. Remember to add a pg_cron job to periodically delete old rows from `cron.job_run_details`. In fact the clean up job would actually be sufficient on its own (bc it generates a row in job_run_details), but that's a pretty subtle/non-obvious solution. Someone could easily come around and reasonably refactor to run it less often, breaking the fix.

So with the cron job you're replicating at least one row / minute and your replication lag should converge to ~60s. If there's some breakdown between the primary and replica, you'll stop replicating and start seeing the lag grow again.

If you're replicating via object storage, your lag will converge to whatever the flush interval is for WAL files. I've seen this controlled primarily by `archive_timeout` but maybe there are some other settings that control this.
