### ISSUE TITLE
Logical database management CRD

### ISSUE THREAD

**Issue by laurivosandi** [cloudnative-pg/cloudnative-pg#2055]
Please add CRD to manage logical databases in a cluster. This probably should be followed by decomposition of role and user CRD-s as well

**Comment by laurivosandi** [comment]
Thanks for the #497 reference

I think users and roles should be *decomposed* into separate CRD-s

**Comment by sxd** [comment]
@laurivosandi well you can continue on the discussion! :D for sure we read everything and every time we can we talk about this issue, also you can join the bi-weekly meeting if you would like to talk more directly and provide your reasons!

I'm closing this since it's not considered an issue yet

Regards!
