### ISSUE TITLE
Error Certificate signed by unknown authority log messages

### ISSUE THREAD

**Issue by adminnz** [cloudnative-pg/cloudnative-pg#2276]
We are seeing these log message from our pods:

```
{
"level":"info",
"ts":"2023-06-14T02:39:45Z",
"logger":"Replicator",
"msg":"synchronizing replication slots",
"logging_pod":"pg-database-2",
"err":"getting replication slot status from primary: failed to connect to `host=pg-database-rw user=streaming_replica database=postgres`: tls error (x509: certificate signed by unknown authority)"
}

{
"level":"info",
"ts":"2023-06-14T02:39:45Z",
"logger":"postgres",
"msg":"record",
"logging_pod":"pg-database-1",
"record":{
	"log_time":"2023-06-14 02:39:45.218 UTC",
	"process_id":"1686086",
	"connection_from":"10.16.17.122:53842",
	"session_id":"64892871.19ba46",
	"session_line_num":"1",
	"session_start_time":"2023-06-14 02:39:45 UTC",
	"transaction_id":"0",
	"error_severity":"LOG",
	"sql_state_code":"XX000",
	"message":"could not accept SSL connection: No error information",
	"backend_type":"not initialized",
	"query_id":"0"
	}
}
```

When i run `kubectl cnpg status pg-database`

I get the following:
```
Certificates Status
Certificate Name         Expiration Date                Days Left Until Expiration
----------------         ---------------                --------------------------
pg-database-ca           2023-09-01 21:46:15 +0000 UTC  79.79
pg-database-replication  2023-09-01 21:46:15 +0000 UTC  79.79
pg-database-server       2023-09-01 21:46:15 +0000 UTC  79.79
```

What is the cause of this, and how do we resolve it ?

**Comment by adminnz** [comment]
Some more information, this appears to have started happening the moment the cluster updated the certificates

**Comment by adminnz** [comment]
Looking in each pod's /controller/certificates directory I can see 

- client-ca.crt
- server-ca.crt
- server.crt
- server.key
- streaming_replica.crt
- streaming_replica.key
And these are identical between the two pods.

Looking at the details of the .crt files they all have the correct NotBefore & NotAfter dates (2023-06-03/2023-09-01) respectively.

**Comment by bennesp** [comment]
Did you find a solution to this? I encountered this today and I deleted and recreated the database since it was a dev environment but I am interested in having a real solution to this

**Comment by adminnz** [comment]
No I didn't find any solution. But it did fix itself after about 15 days (I didn't do anything).

**Comment by sxd** [comment]
Hi @adminnz @bennesp 

After looking into this issue, the problem is that we refresh the files for the certificates and the CA in the primary_conninfo, but after the reload, PostgreSQL doesn't detect that these files changed, hence, it's not restarting the connection and/or reloading the new certificates then still using the old ones and trying to connect.

The workaround for now, is just restart the pod `kubectl cnpg restart <cluster-name> <pod>` and that will reload and restart all the connections once again.

We will try to work with PostgreSQL devs to find a solution in a future release.

Regards!

**Comment by agramner** [comment]
Created a script that renew all the certificates manually using `openssl` and `kubectl patch secret...`. Couldn't trigger the error using this method.

**Comment by agramner** [comment]
I’ve done some more investigations:
 - Created a script that renews the certificates (with `kubectl patch secret...`) and after I’ve run that I get the certificate error in the logs of both replicas but if I restart one of the replica pods that pod stops logging the error (but the other replica still logs the error).
 - From inside a replica pod I compared the primary server certificate fingerprint with the certificates in /controller/certificates, using openssl to connect to the primary, and they match. So think it looks like the the primary server use the new certificates without requiring restart.
 - I follow the code of the `Replicator` and think it looks like the `pgx` code reads the certificates on `ParseConfig` (see https://github.com/jackc/pgx/blob/6f2ce92356f35263258ef7baa4cde86a3e1c6255/pgconn/config.go#L719C1-L719C1). The DB connection seem to be cached by the connection pool. Couldn’t this mean that client won’t use the new certificates when they are updated on disk?

**Comment by karlbohlmark** [comment]
This is has caused several outages for us, @sxd do you have any tracking issue in postgreSQL for this?

**Comment by arusa** [comment]
@agramner this is a real problem in my opinion. I once had an issue that also filled up the WAL volume. That's why I now have very good monitoring and early notifications if that happens again. Those notifications now led me to find out that one cluster had exactly this certificate problem. Now I added another alert watching my logs for "write failed", because the cluster looked completely fine using `kubectl cnpg status CLUSTER` although there were errors in the logs and the volume was filling up.

**Comment by engnatha** [comment]
Is this caused by the generated CA secret not having the `cnpg.io/reload` label applied?
