### ISSUE TITLE
can't change ownership of folder

### ISSUE THREAD

**Issue by eolouw** [cloudnative-pg/cloudnative-pg#2356]
Hi All, I have the cnpg opperator running in my EKS cluster. I have that connected to an EFS storage class.
I want to change the PGDATA to be /data how can I achieve that?
```dockerfile
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dev
spec:
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: app
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: postgresql
      volumeMode: Filesystem
``` 

This is so I can run postgresql on the efs system as it cant change the ownership of the /var/lib/postgresql/data/pgdata\” 
If I do a normal deployment as seen below with the PGDATA value changes it works, so now I am looking to reproduce it in the operator?
```dockerfile
      - name: PGDATA 
          value: /data
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
```

**Comment by sxd** [comment]
Hi @eolouw 

Changing the path of PGDATA is not something the operator allows.
If you can't change the ownership of the FS probably you may want to start looking into another solution. Also, probably looking into EFS and check if it properly support PostgreSQL fs.

Closing since this is not an issue on the operator but rather a problem with an external storage driver.

Regards,
