### ISSUE TITLE
failover triggered due to sessions running out

### ISSUE THREAD

**Issue by smiyc** [cloudnative-pg/cloudnative-pg#2420]
Operator version: 1.20.1
K8s version: 1.23.12 (PKS 1.14.3-build.16)

Description:
When using up all connections (max_connections minus superuser_reserved_connections) it seems that a failover is triggered because the primary can't be connected to check the status.

Steps to repoduce:
1. create a 3 instance (instances: 3, minSyncReplicas: 1, max_connectinos=200, superuser_reserved_connections: "10") --> keycloak-int-cluster.yaml
2. connect with more then 190/200 sessions

Slack Link:
https://cloudnativepg.slack.com/archives/C03AX0J5P29/p1688718561779829
[keycloak-int.zip](https://github.com/cloudnative-pg/cloudnative-pg/files/11981432/keycloak-int.zip)

**Comment by MichaluxPL** [comment]
I can confirm - have exactly the same situation lately.
Worst part of this is the failover cannot succeed in such a conditions, so the cluster becomes unstable and stays that way.

**Comment by MichaluxPL** [comment]
I've made some tests.
Environment: cluster with replica with max_connections=4 and superuser_reserved_connections=3
I've opened one regular user connection, so depleted all available non-superuser connections.
Cluster stayed stable - no failover initiated, rediness probe not complaiinig about DB availability.
Than I've changed max=2, reserved=1 and opened on regular user session and 1 postres users session. That immediatelly triggered the rediness probe fail and initiated failover (which didn't succeed). After closing potgres user session, cluster went back to a normal state.
So IMHO in Your case there are some sessions that use superuser privileges and deplete superuser reserved pool.
That leads to rediness probe fail, since it is using postgres account to connecto to the DB and finaly to a failover.

**Comment by smiyc** [comment]
...for the record: The operator is working as expected.
To sum up the Slack Therad: the failing liveness probe is using pg_isready which is using the postgres user to check the instance and therefore "superuser_reserved_connections" are used.
In my case, during some tests, the application user was granted superuser rights and therefore was able to eat up all connections, causing the liveness probe to fail.
