### ISSUE TITLE
cnpg operator report failed to get deployment name

### ISSUE THREAD

**Issue by litaocdl** [cloudnative-pg/cloudnative-pg#247]
cnpg report failed to get deployment name if it is installed in a different namespace.

**Comment by sxd** [comment]
I don't think that the approach in the #248 make actual sense since we're not using the native approach, we should let the user specify the namespace on which look for the operator deployment and not try a magic approach to find the deployment.

We should use the option `-n` in the plugin to get the operator deployment or the default namespace in the current configuration, so we can follow the Kubernetes style to get objects information.

**Comment by gbartolini** [comment]
@sxd next time please don't forget to update the issue with the actual updates in the PR. Your changes fixed the behavior and that's why you merged the patch. ;)
