### ISSUE TITLE
Introducing the OLM installation method 

### ISSUE THREAD

**Issue by kelpoole** [cloudnative-pg/cloudnative-pg#2592]
Dear CloudNativePG maintainers,

I’m the VP of Product Management at EDB, and also the product manager of Kubernetes related products at EDB.

As you are aware, in May 2022, EDB decided to open source the [Cloud Native PostgreSQL operator](https://cloudnative-pg.io/documentation/current/release_notes/edb-cloud-native-postgresql/) (as it was called back then) and form a new openly governed community around the [newborn CloudNativePG operator](https://www.enterprisedb.com/blog/introducing-cloudnativepg-new-open-source-kubernetes-operator-postgres), following our visionary goal and mission to run Postgres anywhere.

Back then, we could only hope that CloudNativePG would make such an impact. 15 months later, and almost 1700 stars on Github, we are really pleased to see the increasing adoption of CloudNativePG in Kubernetes environments, and most importantly the technical feedback we are receiving from users in this community and from our customer base at EDB.

We’ve recently been seeing an increasing demand to run CloudNativePG on the Red Hat OpenShift platform. As you probably know, EDB has its own certified operator that is a fork of CloudNativePG, called [EDB Postgres for Kubernetes](https://catalog.redhat.com/software/container-stacks/detail/5fb41c88abd2a6f7dbe1b37b).

We are aware of the [current position of the CloudNativePG maintainers not to support OpenShift](https://cloudnative-pg.io/documentation/current/supported_releases/#support-status-of-cloudnativepg-releases) as a Community, and we respect that. However, with this proposal we are asking to reconsider it, even partially.

EDB is willing to:

* Donate the Operator Lifecycle Manager (OLM) bundle for EDB Postgres for Kubernetes, in an adapted form for CloudNativePG, to this community
* Sponsor development time of some of their engineers to introduce a new way in the source code to install the CloudNativePG operator via OLM on any of the supported Kubernetes versions, regularly maintained and published on OperatorHub.io
* Maintain, in case the community does not want to, a Community Operator ([as defined by RedHat](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators)) on the [Red Hat Community Operators repository](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators)
* Maintain a Certified Operator for CloudNativePG that is sponsored and supported by EDB for those companies interested and needing certification. Please provide any guidance or stipulations on how to name the operator in the [RedHat Ecosystem catalog](https://catalog.redhat.com/software/search?target_platforms=Red%20Hat%20OpenShift) so that it does not hinder future trademarks or CNCF Sandbox acceptance.

As one of the leading contributors to the open source PostgreSQL project, our goal is to enable fast prototyping and adoption of Postgres on all Kubernetes platforms (including OpenShift), and at the same time provide professional support to those companies willing to trust EDB on the OpenShift, CloudNativePG and PostgreSQL stack.

Other open source Postgres operators in the market (notably Crunchy, Zalando, Ongres, and Percona), already provide OpenShift support. We’d like to see CloudNativePG considered as an additional open source option in the market, and not be excluded from consideration simply because it lacks OpenShift support.

We are looking forward to your response.

Thank you,
Kelly Poole

**Comment by phisco** [comment]
Dear Kelly,

First and foremost, thank you for opening up this issue. On behalf of all the maintainers, we are extremely pleased and thrilled to receive this sort of commitment from EDB on such an important topic: CloudNativePG on Red Hat OpenShift.

This is definitely the sign that our operator is increasing its adoption not only on the Community side, but also on the enterprise one, in perfect alignment with the mission of this project.

For the time being we have decided to stick with the current position not to support OpenShift at the Community level. The main reason for this is the impossibility for us to automatically test the operator on OpenShift using the current E2E tests infrastructure in GitHub. Given that end users need professional assistance for their production environments, we encourage companies like EDB to take initiative in this area and provide support (such vendors can add themselves to this page: https://cloudnative-pg.io/support/).

We have decided to accept your offer to donate to this community in the form of one or more pull requests the existing OLM bundle for EDB Postgres for Kubernetes, properly adapted for CloudNativePG, and to sponsor development time of your engineers to introduce and maintain the OLM installation method, including publishing on OperatorHub.io via automated pipelines.

We will be happy to introduce the required E2E tests for OLM installation on all supported Kubernetes versions, for every CloudNativePG minor version - starting from the one introducing this feature (i.e. 1.21 or 1.22).

EDB will be mentioned in the metadata of the Cluster Service Version (CSV) as initial creator and contributor for the OLM bundle. The engineers involved in the OLM bundle will be mentioned in the list of the maintainers for the operator, preferably using their business account email as a fair way to recognize the contribution from their company. This will encourage other companies to contribute and help the Community in this endeavor. 

As far as adding the OLM bundle on the Red Hat Community catalog is concerned, we believe that there should be a single one, maintained by the CloudNativePG Community - although we cannot prevent any company from doing that.
However our official position is to defer any decision about this for the time being and re-evaluate it once we have a better understanding of the impact of the Community OLM bundle on OperatorHub.io. Such a position is also coherent with the aforementioned impossibility to automatically test on OpenShift.

The final point is about the certified operator. Our understanding is that Red Hat certified operators are reserved to ISVs, and as such the Community will never be able to provide one. We encourage vendors like EDB to provide a certified version of the CloudNativePG operator and contribute to the growth of the adoption of Postgres in Kubernetes environments. Regarding the naming of the operator, our advice is to use the Linux Foundation trademark usage guidelines for it, which you can find at https://www.linuxfoundation.org/legal/trademark-usage. This is a conservative advice as there is no real and current obligation to respect that, but our aspiration is still to pursue the CNCF graduation process. Should that ever happen, you might be forced to change the name at that point due to the trademark reasons explained in the link above.

Thank you again for raising this. We hope we have provided an answer to all your points, and we are looking forward to the first contributions on the OLM side of things for the supported Kubernetes versions.

Regards,
Philippe, on behalf of all the CloudNativePG Maintainers

**Comment by barthalion** [comment]
Hey folks, I know this is not helpful, but is this still going to happen? Over at GNOME, we're currently using Crunchy Data's operator on our OpenShift cluster. While it works well, it became increasingly obvious to me that it shouldn't be used for production workloads without paying for support first, and I'm evaluating what we could switch to at some point. I would be happy to help with testing this on our cluster if it makes anything easier.

**Comment by sxd** [comment]
@barthalion this has been something that is there since October last year =) you can check the red hat catalog and also here https://operatorhub.io/operator/cloudnative-pg

Regards!

**Comment by ibotty** [comment]
Can you also add the operator to `okd-operators`?  Thank you!
