### ISSUE TITLE
[Feature]: kube-image-keeper url support

### ISSUE THREAD

**Issue by devthejo** [cloudnative-pg/cloudnative-pg#3480]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

I use this tool: [kube-image-keeper](https://github.com/enix/kube-image-keeper), that is rewriting pod image to target a local cache, so the image is prefixed by `localhost:7439/` as `localhost:7439/ghcr.io/cloudnative-pg/postgis:16-3.4` but the controller doesn't understand the replaced image url and make the false assumption that is an old image, so we get this `Upgrading cluster Restarting instance cnpg-3, because: the instance is using an old init container image: localhost:7439/ghcr.io/cloudnative-pg/postgis:16-3.4 -> ghcr.io/cloudnative-pg/postgis:16-3.4`, then kube-image-keeper is rewriting the image and we get an upgrading loop.
I can workaround by disabling kube-image-keeper on theses pod using
```yaml
inheritedMetadata:
  labels:
    kube-image-keeper.enix.io/image-caching-policy: ignore
```
on the cluster manifest, as in this issue: https://github.com/cloudnative-pg/cloudnative-pg/issues/1993
but I would prefer continue using kube-image-keeper with cnpg too :-)

### Describe the solution you'd like

expose an option to allow some custom extract version regex from images url (more flexible and allow custom user image), this could be exposed as an option of cluster spec

### Describe alternatives you've considered

detect this specific url format, and remove this prefix automatically, simpler but not really universal (will work only for kube-image-keeper but there can be other tools like this one with other url formats)

### Backport?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cnolick** [comment]
Hey, I ran into the same error, but this didn't help me out - kube-image-keeper.enix.io/image-caching-policy

The issue persists:

`{"level":"info","ts":"2024-02-02T19:53:19Z","msg":"Recreating instance pod","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"kekos","namespace":"cnpg"},"namespace":"cnpg","name":"kekos","reconcileID":"197d194f-ac42-49ac-8de9-5959fceae65d","uuid":"b66e739d-c204-11ee-be1c-0e6ca50095e4","pod":"kekos-2","to":"ghcr.io/cloudnative-pg/postgresql:13.6","reason":"Restarting instance kekos-2, because: the instance is using an old init container image: ghcr.io/cloudnative-pg/cloudnative-pg@sha256:89cca05e1d2441361e2f057cc1b46af7cbe6602a356cbdb446a3e691c40eb424 -> ghcr.io/cloudnative-pg/cloudnative-pg:1.22.1"}`

**Comment by sxd** [comment]
Closing since this it's going to be handled with the new image catalog idea
