### ISSUE TITLE
[Feature]: Allow to override the default of self-healing when readyReplicas = 0

### ISSUE THREAD

**Issue by vincepower** [cloudnative-pg/cloudnative-pg#3969]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

In some PostgreSQL clusters we operate, the possibility of data loss is considered worse than a potentially unresponsive cluster. This likely hood of losing all replicas is extremely low but it is not zero.

### Describe the solution you'd like

The best approach I can think of is to have an option in the spec like EnforceMinReplicas as a true/false, which is then evaluated as part of the logic in GetSyncReplicasData in cluster_configuration.go.

### Describe alternatives you've considered

I can't see another path forward as we are trying to standardize on CloudNative PG for our internal deployments.

### Additional context

While the change seems small, and I can contribute it, I do not know the impact. So feel free to provide feedback on this idea.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gbartolini** [comment]
Let's assume we are adding `.spec.enforceMinSyncReplicas` to the API, and for back compatibility we default it to `false`. If users want to prioritize consistency over availability, they only have to set it to `true` like in the following example:

```yaml
  minSyncReplicas: 1
  maxSyncReplicas: 1
  enforceMinSyncReplicas: true
```

This will prevent CloudNativePG from ignoring `minSyncReplicas` in case `readyReplicas` is 0.

Any feedback?

**Comment by vincepower** [comment]
That makes sense to me, and I'm good with it. I'll start digging through and getting a PR ready.

I had just figured a cluster configuration parameter makes it more user driven and easier to change.

**Comment by vincepower** [comment]
Just an update: I have the easy part done where it reads in the parameter and won't reduce the minSyncReplicas until the available replicas hit zero, then it still disables replication.

I'm working through it, and seeing how small of a change I can get away with to handle that part.

**Comment by gbartolini** [comment]
any news @vincepower?

**Comment by gbartolini** [comment]
What about `minSyncReplicasEnforcement` accepting `preferred` (current default) or `required`? And in a future version make required the default (to facilitate DBAs transition). We could even think of an annotation instead. Thoughts?

**Comment by leonardoce** [comment]
> What about minSyncReplicasEnforcement accepting preferred (current default) or required? And in a future version make required the default (to facilitate DBAs transition). We could even think of an annotation instead. Thoughts?

That would be clearer in my opinion.

**Comment by fcanovai** [comment]
> What about `minSyncReplicasEnforcement` accepting `preferred` (current default) or `required`? And in a future version make required the default (to facilitate DBAs transition). We could even think of an annotation instead. Thoughts?

I'd rather have `minSyncReplicasEnforcement` `preferred`/`required` than `enforceMinSyncReplicas` `true`/`false`, because in the second one the `minSyncReplicas` seems completely disregarded. I'm not keen on annotations, they won't appear in the api documentation, and people may miss them more easily.

**Comment by mnencia** [comment]
I vote for the `minSyncReplicasEnforcement=preferred/required` field for the reasons Francesco has explained.

**Comment by gbartolini** [comment]
Awesome, let's proceed then. Please bear with me a bit longer. Shall we have:

1. `.spec.minSyncReplicasEnforcement`, or
2. `.spec.postgresql.minSyncReplicasEnforcement`

Although min and max are on the root, I'd rather move this parameter inside the PostgreSQL section, as it is really a refinement when dealing with PostgreSQL (instead of an architectural aspect). Thoughts?

**Comment by leonardoce** [comment]
It's `.spec.postgresql.minSyncReplicasEnforcement` for me.
I'd like to have `min/maxSyncReplicas` inside `spec.postgresql` too but, unfortunately, that would break the API.

**Comment by fcanovai** [comment]
I'd like to see it both at the same level of the min parameter it refers to, and in the `spec.postgresql` section. So, no strong opinion, but I think putting it under `spec.postgresql` would be better in the long run.

**Comment by fcanovai** [comment]
On a second though, the interface (and the documentation) will be way to complex.

From the documentation, it's really unclear what the point of `minSyncReplicas` is, unless it gets enforced. And then, if we enforce just the min, what's the point of the max?

Then we can have `prefer` as the default, to avoid breaking the current behaviour, but synchronous replication is actually a "prefer consistency over availability" kind of setting, so it's kind of weird to have in the opposite way.

Not really keen to add parameters to something already unclear.

### Proposal:

We could leave the current behaviour as is, deprecate everything here and have an improved synchronous replication configuration.

We could track:

* the method we want to use (postgresql like, `first` or `any`)
* the number of instances we want in sync. A single number, enforced.

And then improve the configuration to include external clusters. So, instead of considering the amount of replicas only among the instances belonging to the clusters, we could consider extending this creating an ordered list list that contains user-defined entries and how many internal instances we want. Let's say we want to make sure that an instance from local cluster `foo` and the designated primary of a replica cluster `bar` are in sync.

We would want `synchronous_standby_names` to be `FIRST 2(bar, foo-x)`, assuming a three instances cluster with `foo-1` being the primary, and `foo-x` any of the replicas. No more, because in case of a `bar` disconnection having all of them there would allow `foo` to continue operating, breaking the initial requirement. So we may want to put a limit to the amount of internal instances.

We could define:

```
# first, or any
syncReplicaMethod: first
# num_sync in the relevant [PostgreSQL Documentation](https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-SYNCHRONOUS-STANDBY-NAMES)
syncReplicaNumSync: 2
# max number of pods to include in the list from the current cluster
syncReplicaMaxClusterInstances: 1
# an user-defined list of application_names to add before the local ones
syncReplicaNamesPre:
- `bar`
# an user-defined list of application_names to add after the local ones
syncReplicaNamesPost: []
```

This would generate the `synchronous_standby_names` requested above. `syncReplicaMaxClusterInstances` I think is a max value, because we could have less than that amount to actually insert in the `synchronous_standby_names`, e.g.: when a `syncReplicaElectionConstraint` excludes instances from the list we could not reach the defined amount (could we report an error instead of ignoring this? but then what happens if this happens during the life of the cluster?).

Also, whenever an internal pod becomes not ready we should reevaluate the parameter and reload postgresql.

If these parameters are set (at least one of them between `syncReplicaMethod` and `syncReplicaNumSync`) we could default the others and ignore the `mixSyncReplicas`/`maxSyncReplicas` settings.

This could be a stanza of its own if we also deprecate the current `syncReplicaMaxClusterInstances` and move it there.

**Comment by gbartolini** [comment]
I agree entirely with you, Francesco. Thanks for thinking outside the box here and taking the opportunity to reevaluate the whole problem instead of adopting a scar tissue approach.

I'd instead abandon the PR and this ticket and create a new feature request with details from the above comment, planned for 1.25. This would also extend the current behaviour by giving users more flexibility and control over Postgres sync rep configuration.

Thanks for doing this. Let's wait for other maintainers' and users' feedback, and then I will be happy to proceed with the bureaucracy part.

**Comment by mnencia** [comment]
Thanks, Francesco. The approach you outlined is much clearer than the previous interface, allowing the user to fully customize the PostgreSQL behavior. I agree with Gabriele about abandoning the current PR and creating a new enhancement request planned for 1.25.

**Comment by leonardoce** [comment]
It's fine with me too. Let's implement the new approach

**Comment by gbartolini** [comment]
Superseded by #5095 . Abandoning this.
