### ISSUE TITLE
E2E - consistent failure of upgrade test for the 15 beta

### ISSUE THREAD

**Issue by jsilvela** [cloudnative-pg/cloudnative-pg#420]
The only consistent failure in the nightly builds is the upgrade test in the Postgres15beta branches.
See https://github.com/cloudnative-pg/cloudnative-pg/runs/7313093278?check_suite_focus=true

The upgrade tests seem to be the only ones failing in the 15beta branches.

**Comment by litaocdl** [comment]
The failure is because we did not have 15beta1 version verification added into 1.15.1 release.  and for now, even with 1.15.2 and 1.16.0 released, but those two release are in release branch. the upgrade test case still pick the latest recent from main branch (1.15.1)

there is some discussion need here, as we release in release branch, we can have two choices for upgrade test cases
1. copy the released crd from released branch to main. (1.15.2, 1.16.0 .... )
2. run upgrade test case in release branch and skip this case in main branch. 

Any comments

**Comment by mnencia** [comment]
The release files for 1.16.0 are now on main (see https://github.com/cloudnative-pg/cloudnative-pg/commit/d6b9f34502353505270a90876064e1249c34a3c9), but the test is continuing to fail.

**Comment by jsilvela** [comment]
OK, found the issue. Assigning this to myself to fix, will un-assign Tao.
