### ISSUE TITLE
[Feature]: E2E tests should capture the logs for every pod

### ISSUE THREAD

**Issue by sxd** [cloudnative-pg/cloudnative-pg#5053]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Currently we relied on external tools to capture the logs and this lead to lot's of issues when trying to find the logs of the failed tests

### Describe the solution you'd like

The BeforeSuite should set a routine that listen on the namespaces created and the cluster created on each of them, saving the logs in a Buffer to eventually be used.
In case a test fails, this test should call the routine (signal) with the needed information to dump the logs into a destination inside the path that's already being captured by the artifacts.
In case a test is succeeded, the routine should be signaled and just discard the Buffer with the logs.

### Describe alternatives you've considered

Just keep everything as it is

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fcanovai** [comment]
I'm trying a different approach. The main difference is using stern as a library instead of the plugin code, writing to a pipe and then dispatching the resulting lines to a file representing the pod. This will allow us to avoid managing informers to follow namespaces and clusters, and also have each container log saved in its own file for clarity.

There is an annoyance though in this approach that I don't like. There is no link between the pod logs and the tests they come from, except namespaces and pods names. When we run ginkgo on multiple nodes, a single stern is watching all the pods, but won't see test results. I think it's time for a refactor where we extract the boilerplate in a single `BeforeEach/AfterEach` that manages namespace creation and namespace watch, based on a configuration struct defined in each test.
