### ISSUE TITLE
[Feature]: Output PostgreSQL logs to a PVC

### ISSUE THREAD

**Issue by xiongcp** [cloudnative-pg/cloudnative-pg#5302]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

Output PostgreSQL logs to a PVC

### Describe the solution you'd like

In the k3s environment, a common logging framework might not be deployed during setup. Therefore, we want to find a way to output logs to a PVC instead of installing additional components to collect logs.

### Describe alternatives you've considered

I’m considering modifying the code, but I’m concerned about potential side effects.

### Backport?

Yes

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
Hello @xiongcp 

What's the intention here? the final goal? Are you using k3s in a development environment and you don't want to install it there, or you're using k3s in production? the intention it's about getting the logs for development purposes? Are you using k3s in edge computing?

Please help us to clarify, because sending the logs into a pvc inside a pod it's  a complete anti-pattern in Kubernetes and it's not something that people should be using, that's why the log collection has standard and useful solution to capture, process, store and post-process the logs in the environment.

Regards,

**Comment by xiongcp** [comment]
Thank you for your response. Yes, we are planning to use k3s in edge computing, but we do not intend to implement centralized log collection because that would require installing a logging and storage service, which consumes significant resources. Instead, we plan to output the logs from the pods to a PVC. Therefore, we are looking for a solution to achieve this. I have also tried modifying the source code, including the logpath and related parameters, but it doesn’t seem to be working.

**Comment by kfox1111** [comment]
fluent-bit to a pvc? Its pretty light weight.

**Comment by xiongcp** [comment]
I want to output the logs directly to NFS or a local path. @kfox1111

**Comment by sxd** [comment]
@xiongcp if you think on using NFS on k3s in edge, well I think that having something like fluent-bit will not be an issue, it's actually more reliable than NFS for sure, I don't think what you're asking is something that will benefit the community and it's going totally out of the scope of being cloud native, you can always (as you look you already did) fork the project and do your changes, but in this particular case we can't try to solve a so specific use case.

On the FluentBit side, the project it's extremely lightweight so I suggest you to try it and test it, since it can be a good improvement on the reliability and how to process the logs in edge, it has many things that are done thinking on edge situations.

**Comment by xiongcp** [comment]
ok ,think you
