### ISSUE TITLE
[Feature]: Support ICU configuration options with `initdb`

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#5386]
### Is there an existing issue already for this feature request/idea?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new feature request to be evaluated.

### What problem is this feature going to solve? Why should it be added?

PostgreSQL 15 introduced support for the ICU library to provide locale services at cluster initialization, through two new options for `initdb`:

- `--icu-locale`
- `--icu-locale-provider`

See: https://www.postgresql.org/docs/current/app-initdb.html

This is related to #5163 

### Describe the solution you'd like

Add two new options in the `.spec.bootstrap.initdb` stanza:

- `localeProvider`, accepting two values: `libc` and `icu` (empty by default)
- `icuLocale`, accepting the locale ID as a string

A valued `icuLocale` requires `localeProvider` set to `icu`. Prevent setting these options with PostgreSQL < 15.

### Describe alternatives you've considered

N/A

### Additional context

At the moment we will not consider the `--icu-rules` option.

### Backport?

No

### Are you willing to actively contribute to this feature?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ardentperf** [comment]
pg17 adds the builtin provider too. It might make sense to add support for both ICU and builtin at the same time.

also, it's a longer conversation, but IIUC the current default locale is explicitly set by CNPG to be "C" https://cloudnative-pg.io/documentation/1.24/bootstrap/#bootstrap-an-empty-cluster-initdb

given this CNPG default, I think there's a very strong argument to be made for switching the default to the built-in "C.UTF-8" locale for postgres v17+

The "C" locale is has been implemented internally by Postgres for many years and actually does not use libc, however it has some usability issues (eg. handling of accented characters). Those usability issues are addressed in the "C.UTF-8" locale without changing code-point sort ordering, and the builtin provider avoids well-documented risks of using an external provider like libc.  (Before v17, the "C.UTF-8" locale was not builtin but used glibc.)

On ICU specifically - probably need to think through how users will manage ICU versions and long-term maintenance specifically in the k8s & container context, since upgrading an ICU version will generally bring sort order changes.
