### ISSUE TITLE
Prevent recovery object store and backup object store from being the same location

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#62]
When boostrapping a new cluster from a recovery object store, make that, if specified, the backup object store is not identical. This should be intercepted at the earliest phase in the configuration phase using a webhook.

**Comment by NiharDudam** [comment]
Does this mean if I delete a cluster, I cannot use the backup location anymore except for restore? and I need to change my backup path on every restore?

**Comment by jsilvela** [comment]
> and I need to change my backup path on every restore?
This patch does not prevent the general case of backup locations being the same for two clusters.
It is a top-level check to ensure a recovery does not backup into its source.
Issue #61 will be the fuller fix.

**Comment by gbartolini** [comment]
> Does this mean if I delete a cluster, I cannot use the backup location anymore except for restore?

That's a fairly accurate summary and, based on our experience, a sensible thing to do - by default at least. If that helps, what we have seen working very well in managing large databases for many years, a fully recovered cluster is considered as a new cluster.

The workaround however is pretty simple: use a different path or just a different `serverName` under `barmanObjectStore`, either in the external cluster spec (recovery object store) or under the `backup` section of the cluster (backup object store).

**Comment by NiharDudam** [comment]
ok thanks. So just to clarify my thoughts here. Please correct me if needed.

- 2 clusters with the same name cannot share the same backup path 
- 2 clusters with different names can share the same backup path because 2 different folders are used 
- If you delete a cluster, the backup path can only be used to restore onto a different cluster 
- After/During restore, the backup path cannot be the same as the restored path as it has data in it, and restored cluster is considered a new cluster 

and these checks are enforced in webhook and also at controller level I assume?
