### ISSUE TITLE
Add "hibernate on" command to kubectl plugin

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#781]
Add the following command to the `cnpg` plugin for `kubectl`:

```console
kubectl cnpg hibernate on [-n NAMESPACE] <CLUSTER_NAME>
```

As a result, the plugin will be:

- Fencing the cluster
- Destroying one standby at a time, including their own PVCs
- Destroying the primary by keeping the PVC group, by removing the ownership metadata
- Adding the necessary annotations (to be determined) to all PVCs, in particular the cluster information, excluding the status

**Comment by sxd** [comment]
Reading the code I found a bit odd the idea of `hibernate on` and `hibernate off`, because you cannot turn off the hibernation, following the same concept of hibernation that we have in the laptop I think that we should use the commands like this:

```
kubectl hibernate <cluster>
kubectl resume <cluster>
```
That will replace `hibernate on` and `hibernate off`, with a more generic way to understand the command itself and what it will do.

On the other hand, having in the `kubectl status <cluster-name>` command the information that the cluster it's in "hibernation" state will provide a really useful tool for users.

**Comment by mnencia** [comment]
I agree with @leonardoce about keeping the two commands related. There is also the `hibernate status` subcommand to keep in mind.
